# Generated by Django 4.0.4 on 2022-05-18 18:27

import accounts.models
import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.get_resume_path, validators=[common.utils.validate_resume_file_extension], verbose_name='CV/Resume'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
