# Generated by Django 4.0.4 on 2022-04-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Entry Level'), (2, 'Mid Level'), (3, 'Senior Level')], null=True),
        ),
    ]
