# Generated by Django 4.0.4 on 2022-05-18 18:27

import common.utils
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default='NONE', upload_to=jobs.models.get_resume_path, validators=[common.utils.validate_resume_file_extension], verbose_name='CV/Resume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Short Listed'), (3, 'Archived')], default=0),
        ),
    ]
